version: '2.1'
services:
  client:
    build:
      context: ./client/
    volumes:
      - './client:/usr/src/client'
      - '/usr/src/client/node_modules'
    ports:
      - '3000:3000'
    links:
      - server
    depends_on:
      - server
    networks:
      - rezbuild
  server:
    build:
      context: ./server/
    volumes:
       - './server:/usr/src/server'
       - '/usr/src/server/node_modules'
    ports:
      - '3001:3001'
    links:
      - db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:27017
    networks:
      - rezbuild
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - rezbuild
networks:
    rezbuild:
        driver: bridge