var common = {    
    LANES: {
        BACKLOG: 'lane_backlog',
        TODO: 'lane_todo',
        DONE: 'lane_done',
    },
    ROLES: {
        CUSTOMER: {name: 'Customer', description: 'A customer...', actions: []},
        ANALYST: {name: 'Analyst', description: 'An analyst...', actions: ['KPI_ECONOMICAL_ASIS', 'KPI_SOCIAL_ASIS', 'KPI_ENERGICAL_ASIS', 'KPI_COMFORT_ASIS', 'KPI_ECONOMICAL_TOBE', 'KPI_SOCIAL_TOBE', 'KPI_ENERGICAL_TOBE', 'KPI_COMFORT_TOBE']},
        DESIGNER: {name: 'Designer', description: 'A designer...', actions: ['MODEL_ASIS', 'MODEL_TOBE']},
    },
    STATUS: {
        INIT: ['MODEL_ASIS'],
        MODEL_ASIS: ['MODEL_ASIS', 'KPI_ECONOMICAL_ASIS', 'KPI_SOCIAL_ASIS', 'KPI_ENERGICAL_ASIS', 'KPI_COMFORT_ASIS', 'MODEL_TOBE'],
        MODEL_TOBE: ['MODEL_TOBE', 'KPI_ECONOMICAL_TOBE', 'KPI_SOCIAL_TOBE', 'KPI_ENERGICAL_TOBE', 'KPI_COMFORT_TOBE'],
        KPI_ECONOMICAL_ASIS: ['KPI_ECONOMICAL_ASIS'],
        KPI_SOCIAL_ASIS: ['KPI_SOCIAL_ASIS'],
        KPI_ENERGICAL_ASIS: ['KPI_ENERGICAL_ASIS'],
        KPI_COMFORT_ASIS: ['KPI_COMFORT_ASIS'],
        KPI_ECONOMICAL_TOBE: ['KPI_ECONOMICAL_TOBE'],
        KPI_SOCIAL_TOBE: ['KPI_SOCIAL_TOBE'],
        KPI_ENERGICAL_TOBE: ['KPI_ENERGICAL_TOBE'],
        KPI_COMFORT_TOBE: ['KPI_COMFORT_TOBE']
    },
    ACTIONS: {
        MODEL_ASIS: {
            description: 'Upload the 3D model of the building as it is.',
            names: ['ASIS model'],
            formats: ['.ifc'],
            typeValues: [Object],
            values: [''],
            minValues: [''],
            maxValues: [''],
            priorities: [true],
        },
        KPI_ECONOMICAL_ASIS: {
            description: 'Assess the economical quality of the 3D model of the building as it is.',
            names: [
                'Payback period',
                'Internal rate of return',
                'Life cycle cost',
                'Net present value',
                'Return on rquity',
                'Incremental discounted payback period',
                'Change in value of buildings property',
                'Payback time',
                'Return on investments',
                'Annual costs',
            ],
            formats: [
                'years',
                '%',
                'k€',
                '€',
                '%',
                'years',
                '€',
                'years',
                '%',
                '€',
            ],
            typeValues: [
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
            ],
            minValues: [
                25,
                5,
                0,
                0,
                5,
                5,
                0,
                5,
                0,
                0,
            ],
            values: [
                25,
                5,
                0,
                0,
                5,
                5,
                0,
                5,
                0,
                0,
            ],
            maxValues: [
                5,
                25,
                200,
                1000000,
                25,
                25,
                100,
                25,
                25,
                3000,
            ],
            priorities: [
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
            ],
        },
        KPI_ENERGICAL_ASIS: {
            description: 'Assess the energy quality of the 3D model of the building as it is.',
            names:[
                "Primary electric energy demand",
                "Primary thermal energy demand",
                "Total electric and thermal energy consumption per gross surface unit",
                "Primary energy demand reduction",
                "Electrical energy bill per gross internal surface unit",
                "Thermal energy bill per gross internal surface unit",
                "Building heat transfer coefficient (U value)",
                "Electric energy consumption per gross surface unit",
                "Use of renewable energy",
                "Thermal energy consumption per gross surface unit",
                "Reduction in annual final energy consumption",
                "Percentage of Renewable energy use",
                "Reduction in lifecycle CO2 emissions in tonnes",
                "Energy savings",
                "Reduction of CO2",
                "Annual final energy consumption",
                "Sustainable resource use",
                "Carbon dioxide emission in tonnes reduction",
                "Energy class of the building",               
                ], //38
                formats: [
                    "toe",
                    "toe",
                    "(toe/m2* y)*1000",
                    "%",
                    "€/ m2 *y",
                    "€/ m2 *y",
                    "kW/m2/K",
                    "kWhe/m2 *y",
                    "",
                    "kWht/m2 *y",
                    "% in kWh",
                    "%",
                    "%",
                    "kWh",
                    "tCO2",
                    "kWh/y",
                    "% ",
                    "%",
                    "A-G",

                ],
                typeValues: [
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Boolean,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                ],
                minValues: [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                values: [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                maxValues: [
                    2,
                    2,
                    4,
                    100,
                    40,
                    100,
                    10,
                    200,
                    1,
                    500,
                    100,
                    100,
                    100,
                    15000,
                    5,
                    15000,
                    100,
                    100,
                    6,
                ],
                priorities: [
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    true,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    true,
                ],
        },
        KPI_SOCIAL_ASIS: {
            description: 'Assess the social quality of the 3D model of the building as it is.',
            names:[
                "Occupant satisfaction",
                "Arrears on utility bills",
                "Hidden energy poverty",
                "High share of energy expenditure in income",
                "Inability to keep home adequately warm",
                "Fuel oil prices",
                "Biomass prices",
                "Household electricity prices",
                "District heating prices",
                "Household gas prices",
                "Dwelling comfortably cool during summer time",
                "Dwelling comfortably warm during winter time",
                "Presence of leak, damp, rot",
                "Installation time reduction",                          
                ], //38
                formats: [
                    'pts',
                    'months',
                    '€',
                    '€',
                    '%',
                    '€',
                    '€',
                    '€c',
                    '€c',
                    '€',
                    'pts',
                    'pts',
                    '',
                    '%',
                ],
                typeValues: [
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Boolean,
                    Number,
                ],
                minValues: [
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    5,
                    2,
                    0,
                    1,
                    1,
                    0,
                    0,
                ],
                values: [
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    5,
                    2,
                    0,
                    1,
                    1,
                    0,
                    0,
                ],
                maxValues: [
                    5,
                    3,
                    1000000,
                    1000000,
                    100,
                    1000000,
                    1000000,
                    30,
                    20,
                    1000000,
                    5,
                    5,
                    1,
                    100,
                ],
                priorities: [
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false
                ]
        },
        KPI_COMFORT_ASIS: {
            description: 'Assess the comfort quality of the 3D model of the building as it is.',
            names:[
                "Room temperature",
                "Thermal comfort / Humidity",
                "CO2 concentration",
                "Formaldehyde (HCHO) concentration",
                "% time inside the hygrothermal zone",
                "Total VOCs (PM2.5, PM10, PM20)"                                   
                ], //38
                formats: [
                    '°C',
                    '%',
                    'mg/m3, ppm',
                    'mg/m3, ppm',
                    '%',
                    'ug/m3, ppm',
                ],
                typeValues: [
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                ],
                minValues: [
                    5,
                    30,
                    200,
                    0,
                    0,
                    0,
                ],
                values: [
                    5,
                    30,
                    200,
                    0,
                    0,
                    0,
                ],
                maxValues: [
                    45,
                    100,
                    2000,
                    2000,
                    100,
                    100,
                ],
                priorities: [
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                ]
        },
        MODEL_TOBE: {
            description: 'Upload the 3D model of the building as it will be.',
            names: ['TOBE model'],
            formats: ['.ifc'],
            typeValues: [Object],
            values: [''],
            minValues: [''],
            maxValues: [''],
            priorities: [true],
        },
        
        KPI_ECONOMICAL_TOBE: {
            description: 'Assess the economical quality of the 3D model of the building as it will be.',
            names: [
                'Payback period',
                'Internal rate of return',
                'Life cycle cost',
                'Net present value',
                'Return on rquity',
                'Incremental discounted payback period',
                'Change in value of buildings property',
                'Payback time',
                'Return on investments',
                'Annual costs',
            ],
            formats: [
                'years',
                '%',
                'k€',
                '€',
                '%',
                'years',
                '€',
                'years',
                '%',
                '€',
            ],
            typeValues: [
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
                Number,
            ],
            minValues: [
                25,
                5,
                0,
                0,
                5,
                5,
                0,
                5,
                0,
                0,
            ],
            values: [
                25,
                5,
                0,
                0,
                5,
                5,
                0,
                5,
                0,
                0,
            ],
            maxValues: [
                5,
                25,
                200,
                1000000,
                25,
                25,
                100,
                25,
                25,
                3000,
            ],
            priorities: [
                true,
                true,
                true,
                false,
                false,
                false,
                false,
                false,
                false,
                false,
            ],
        },
        KPI_ENERGICAL_TOBE: {
            description: 'Assess the energy quality of the 3D model of the building as it will be.',
            names:[
                "Primary electric energy demand",
                "Primary thermal energy demand",
                "Total electric and thermal energy consumption per gross surface unit",
                "Primary energy demand reduction",
                "Electrical energy bill per gross internal surface unit",
                "Thermal energy bill per gross internal surface unit",
                "Building heat transfer coefficient (U value)",
                "Electric energy consumption per gross surface unit",
                "Use of renewable energy",
                "Thermal energy consumption per gross surface unit",
                "Reduction in annual final energy consumption",
                "Percentage of Renewable energy use",
                "Reduction in lifecycle CO2 emissions in tonnes",
                "Energy savings",
                "Reduction of CO2",
                "Annual final energy consumption",
                "Sustainable resource use",
                "Carbon dioxide emission in tonnes reduction",
                "Energy class of the building",               
                ], //38
                formats: [
                    "toe",
                    "toe",
                    "(toe/m2* y)*1000",
                    "%",
                    "€/ m2 *y",
                    "€/ m2 *y",
                    "kW/m2/K",
                    "kWhe/m2 *y",
                    "",
                    "kWht/m2 *y",
                    "% in kWh",
                    "%",
                    "%",
                    "kWh",
                    "tCO2",
                    "kWh/y",
                    "% ",
                    "%",
                    "A-G",

                ],
                typeValues: [
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Boolean,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                ],
                minValues: [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                ],
                values: [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    6,
                ],
                maxValues: [
                    2,
                    2,
                    4,
                    100,
                    40,
                    100,
                    10,
                    200,
                    1,
                    500,
                    100,
                    100,
                    100,
                    15000,
                    5,
                    15000,
                    100,
                    100,
                    'A',
                ],
                priorities: [
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    true,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    true,
                    true,
                ],
        },
        KPI_SOCIAL_TOBE: {
            description: 'Assess the social quality of the 3D model of the building as it will be.',
            names:[
                "Occupant satisfaction",
                "Arrears on utility bills",
                "Hidden energy poverty",
                "High share of energy expenditure in income",
                "Inability to keep home adequately warm",
                "Fuel oil prices",
                "Biomass prices",
                "Household electricity prices",
                "District heating prices",
                "Household gas prices",
                "Dwelling comfortably cool during summer time",
                "Dwelling comfortably warm during winter time",
                "Presence of leak, damp, rot",
                "Installation time reduction",                          
                ], //38
                formats: [
                    'pts',
                    'months',
                    '€',
                    '€',
                    '%',
                    '€',
                    '€',
                    '€c',
                    '€c',
                    '€',
                    'pts',
                    'pts',
                    '',
                    '%',
                ],
                typeValues: [
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Boolean,
                    Number,
                ],
                minValues: [
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    5,
                    2,
                    0,
                    1,
                    1,
                    0,
                    0,
                ],
                values: [
                    1,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    5,
                    2,
                    0,
                    1,
                    1,
                    0,
                    0,
                ],
                maxValues: [
                    5,
                    3,
                    1000000,
                    1000000,
                    100,
                    1000000,
                    1000000,
                    30,
                    20,
                    1000000,
                    5,
                    5,
                    1,
                    100,
                ],
                priorities: [
                    true,
                    false,
                    false,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false,
                    true,
                    false,
                    false,
                    false
                ]
        },
        KPI_COMFORT_TOBE: {
            description: 'Assess the comfort quality of the 3D model of the building as it will be.',
            names:[
                "Room temperature",
                "Thermal comfort / Humidity",
                "CO2 concentration",
                "Formaldehyde (HCHO) concentration",
                "% time inside the hygrothermal zone",
                "Total VOCs (PM2.5, PM10, PM20)"                                   
                ], //38
                formats: [
                    '°C',
                    '%',
                    'mg/m3, ppm',
                    'mg/m3, ppm',
                    '%',
                    'ug/m3, ppm',
                ],
                typeValues: [
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                    Number,
                ],
                minValues: [
                    5,
                    30,
                    200,
                    0,
                    0,
                    0,
                ],
                values: [
                    5,
                    30,
                    200,
                    0,
                    0,
                    0,
                ],
                maxValues: [
                    45,
                    100,
                    2000,
                    2000,
                    100,
                    100,
                ],
                priorities: [
                    false,
                    true,
                    false,
                    true,
                    false,
                    false,
                ]
        },
    }
}

module.exports = common
