var common = {
    /*PROJECT:{
        GENERAL: {
            name: {name: 'Name', type:'String'},
            country: {name: 'Country', type:'String'},
            city: {name: 'City', type:'String'},
            address: {name: 'Address', type:'String'},
            context: {name: 'Context', type:'String'},
            degree: {name: 'Degree', type:'String'},
            climat: {name: 'Climat', type:'String'},
        },

        NEEDS: {
            refurbishmentExpectations:      {name: 'Refurbishement Expectations', type:'String'},
            energyConsumptionExpectations:  {name: 'Energy Consumption Expectations', type:'String'},
            environmentalExpectations:       {name: 'Environmental Expectations', type:'String'},
            economicalExpectations:         {name: 'Economical Expectations', type:'String'},
            socialExpectations:             {name: 'Social Expectations', type:'String'},
            comfortExpectations:             {name: 'Comfort Expectations', type:'String'},
            differentLocationDuringRenovation: {name: "Don't leave home during renovation", type:'Boolean'},
            elevatorInstallation: {type: Boolean, default: false},
            improvedAccessibility: {type: Boolean, default: false},
            reductionBillAmount: {type: Boolean, default: false},
            moreHomeSpaces: {type: Boolean, default: false},
            brighterEnvironments: {type: Boolean, default: false},
            extraServiceRoom: {type: Boolean, default: false},
            heatingUpgrading: {type: Boolean, default: false},
            coolingUpgrading: {type: Boolean, default: false},
            ventilationUpgrading: {type: Boolean, default: false},
            consumptionControl: {type: Boolean, default: false},
            eliminitationAirInfiltration: {type: Boolean, default: false},
            shadingUpgrading: {type: Boolean, default: false},
            airQualityImprovement: {type: Boolean, default: false},
            noiseReduction: {type: Boolean, default: false},

        },
        BUILDING: {

        },
        GEOMETRY: {

        },
        ENVELOPE: {

        },

    },*/
    
    LANES: {
        BACKLOG: 'lane_backlog',
        TODO: 'lane_todo',
        DONE: 'lane_done',
    },
    ROLES: {
        CUSTOMER: {name: 'Customer', description: 'The customer is...'},
        DESIGNER: {name: 'Designer', description: 'The designer is...'},
        ARCHITECT: {name: 'Architect', description: 'The architect is...'},
    },
    STATUS: {
        INIT: ['MODEL_ASIS'],
        MODEL_ASIS: ['MODEL_ASIS', 'KPI_ECONOMICAL_ASIS', 'KPI_ENVIRONMENTAL_ASIS', 'KPI_SOCIAL_ASIS', 'KPI_ENERGICAL_ASIS', 'KPI_COMFORT_ASIS', 'MODEL_TOBE'],
        MODEL_TOBE: ['MODEL_TOBE', 'KPI_ECONOMICAL_TOBE', 'KPI_ENVIRONMENTAL_TOBE', 'KPI_SOCIAL_TOBE', 'KPI_ENERGICAL_TOBE', 'KPI_COMFORT_TOBE'],
        KPI_ECONOMICAL_ASIS: ['KPI_ECONOMICAL_ASIS'],
        KPI_ENVIRONMENTAL_ASIS: ['KPI_ENVIRONMENTAL_ASIS'],
        KPI_SOCIAL_ASIS: ['KPI_SOCIAL_ASIS'],
        KPI_ENERGICAL_ASIS: ['KPI_ENERGICAL_ASIS'],
        KPI_COMFORT_ASIS: ['KPI_COMFORT_ASIS'],
        KPI_ECONOMICAL_TOBE: ['KPI_ECONOMICAL_TOBE'],
        KPI_ENVIRONMENTAL_TOBE: ['KPI_ENVIRONMENTAL_TOBE'],
        KPI_SOCIAL_TOBE: ['KPI_SOCIAL_TOBE'],
        KPI_ENERGICAL_TOBE: ['KPI_ENERGICAL_TOBE'],
        KPI_COMFORT_TOBE: ['KPI_COMFORT_TOBE']
    },
    ACTIONS: {
        MODEL_ASIS: {
            names: ['ASIS model'],
            formats: ['.ifc'],
            values: ['']
        },
        KPI_ECONOMICAL_ASIS: {
            names: [
                'Internal Rate of Return (IRR)',
                'Required Rate of Return (RRR)',
                'Return on Equity (ROE)',
                'Return on Capital Employed (ROCE)',
                'Incremental Discounted Payback Period',
                'Benefit Cost Ratio (BC Ratio)',
                'National Inflation Rate',
                'Real Estate Assessment to Sales Ratio',
                'Real Estate Coefficient of Dispersion',
                'Pay Back Time (PBT)',
                'Return on Investments (ROI)',

            ],
            formats: [
                '%',
                '%',
                '%',
                '%',
                'years',
                '%',
                '%',
                '%',
                '%',
                'years',
                '%',
            ],
            values: [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
            ]
        },
        KPI_ENERGICAL_ASIS: {
            names:[
                "Energy source typology",
                "Primary electric energy demand",
                "Primary thermal energy demand",
                "Total electric and thermal energy consumption per gross volume unit",
                "Total electric and thermal energy consumption per gross surface unit",
                "Total energy consumption per conditioned surface unit",
                "Electric energy consumption per conditioned surface unit",
                "Electric energy consumption per gross surface unit",
                "Thermal energy consumption per conditioned surface unit",
                "Thermal energy consumption per gross surface unit",
                "Electric energy consumption for conditioning normalized per conditioned surface unit",
                "Thermal energy consumption for conditioning normalized per conditioned surface unit",
                "Energy consumption for lighting per gross surface units",
                "Peak load and profile of electric energy demand",
                "Peak load and profile of thermal energy demand",
                "Total energy cost per gross surface unit",
                "Electrical energy bill per gross internal surface unit",
                "Thermal energy bill per gross internal surface unit",
                "Energy bill for conditioning per conditioned surface unit",
                "Energy bill for lighting per gross internal surface unit",
                "Total annual revenues, sum of discounted annual revenues and annuity",
                "Energy production costs",
                "Building heat transfer coefficient (U value)",
                "Reduction in annual final energy consumption",
                "Total residential electrical energy use per capita (core indicator)", 
                "Use of renewable energy",
                "Percentage of Renewable energy use",
                "Annual final energy consumption", 
                "Carbon dioxide emission in tonnes reduction", 
                "Reduction in lifecycle CO2 emissions in tonnes",
                "CO2 emissions associated with the heating for buildings",
                "CO2 produced from electricity usage per m2 of floor area",
                "Energy performance gap (EPG)",
                "Energy savings",
                "Reduction of CO2",
                "GWP - GhGs",
                "Energy class of the building",
                "Sustainable resource use",
                ], //38
                formats: [
                    "Electric/Thermal/etc.",
                    "toe",
                    "toe",
                    "(toe/m3* y)*1000",
                    "(toe/m2* y)*1000",
                    "(toe/m2 Nrg *y)*1000",
                    "kWhe/m2 Nrg *y",
                    "kWhe/m2 *y",
                    "kWht/m2 Nrg *y",
                    "kWht/m2 *y",
                    "kWhe/m2 Nrg *y",
                    "kWht/m2 Nrg * DD*y",
                    "kWhe/m2 Nrg * DD*y",
                    "kWe",
                    "kWt",
                    "€/ m2 *y",
                    "€/ m2 *y",
                    "€/ m2 *y",
                    "€/ m2Nrg *y",
                    "€/ m2 *y",
                    "€/year",
                    "€/kWh",
                    "kW/m2/K",
                    "% in kWh",
                    "kWh/y/cap",
                    "Yes/no",
                    "%",
                    "kWh/y", 
                    "%", 
                    "%",
                    "tCO2/y",
                    "tCO2/m2",
                    "EPG=(E2-E1)/E1",
                    "Kwh",
                    "tCO2",
                    "kg CO2 eq",
                    "A-G",
                    "% or scale, typology etc."
                ],
                values:[
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                ]
        },
        KPI_ENVIRONMENTAL_ASIS: {
            names: ['LCA Indicator'],
            formats: ['kgCO2eq'],
            values: ['0']
        },
        KPI_SOCIAL_ASIS: {
            names: [
                'Flexibility',
                'Occupant satisfaction',
                'Feeling of safety',
                'Cultural heritage',
                'Increased environmental/sustainability',
                'education',
                'Community acceptance',
                'Arrears on utility bills',
                'Hidden energy poverty(HEP)',
                'Inability to keep home adequately warm',
                'Fuel oil prices',
                'Biomass prices',
                'Coal prices',
                'Household electricity prices',
                'District heating prices',
                'Household gas prices',
                'Dwelling comfortably cool during summer time',
                'Number of rooms per person, owners',
                'Dwelling comfortably warm during winter time',
                'Number of rooms per person, renters',
                'Dwellings in densely populated areas',
                'Number of rooms per person, total',
                'Dwellings in intermediately populated areas',
                'Poverty risk',
                'Dwellings with energy label A',
                'Energy expenses, income quintile 1',
                'Energy expenses, income quintile 2',
                'Energy expenses, income quintile 3',
                'Energy expenses, income quintile 4',
                'Energy expenses, income quintile 5',
                'Equipped with air conditioning',
                'Equipped with heating'
            ],
            formats: [
                'Degree in % or scale',
                '% or scale',
                '% or scale',
                'yes/no',
                'scale or %',
                'scale or %',
                '% or scale',
                '€',
                '€',
                '€',
                '% or scale',
                '€',
                '€',
                '€',
                '€',
                '€',
                '€',
                'number',
                'number',
                'number',
                'number',
                'number',
                'number',
                'number',
                '%',
                'number',
                '€',
                '€',
                '€',
                '€',
                '€',
                'yes/no',
                'yes/no'
            ],
            values: [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        KPI_COMFORT_ASIS: {
            names: [
                'Room temperature',
                'Thermal comfort / Humidity',
                'CO2 concentration',
                'Formaldehyde (HCHO) concentration',
                '% time inside the hygrothermal zone',
                'Total VOCs (PM2.5, PM10, PM20)'
            ],
            formats: [
                '°C degrees',
                '%',
                'mg/m3, ppm',
                'mg/m3, ppm',
                '%',
                'ug/m3, ppm'
            ],
            values: [
                '0',
                '0',
                '0',
                '0',
                '0',
                '0'
            ]
        },
        MODEL_TOBE: {
            names: ['TOBE model'],
            formats: ['.ifc'],
            values: ['']
        },
        
        KPI_ECONOMICAL_TOBE: {
            names: [
                'Internal Rate of Return (IRR)',
                'Required Rate of Return (RRR)',
                'Return on Equity (ROE)',
                'Return on Capital Employed (ROCE)',
                'Incremental Discounted Payback Period',
                'Benefit Cost Ratio (BC Ratio)',
                'National Inflation Rate',
                'Real Estate Assessment to Sales Ratio',
                'Real Estate Coefficient of Dispersion',
                'Pay Back Time (PBT)',
                'Return on Investments (ROI)',

            ],
            formats: [
                '%',
                '%',
                '%',
                '%',
                'years',
                '%',
                '%',
                '%',
                '%',
                'years',
                '%',
            ],
            values: [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
            ]
        },
        KPI_ENERGICAL_TOBE: {
            names:[
                "Energy source typology",
                "Primary electric energy demand",
                "Primary thermal energy demand",
                "Total electric and thermal energy consumption per gross volume unit",
                "Total electric and thermal energy consumption per gross surface unit",
                "Total energy consumption per conditioned surface unit",
                "Electric energy consumption per conditioned surface unit",
                "Electric energy consumption per gross surface unit",
                "Thermal energy consumption per conditioned surface unit",
                "Thermal energy consumption per gross surface unit",
                "Electric energy consumption for conditioning normalized per conditioned surface unit",
                "Thermal energy consumption for conditioning normalized per conditioned surface unit",
                "Energy consumption for lighting per gross surface units",
                "Peak load and profile of electric energy demand",
                "Peak load and profile of thermal energy demand",
                "Total energy cost per gross surface unit",
                "Electrical energy bill per gross internal surface unit",
                "Thermal energy bill per gross internal surface unit",
                "Energy bill for conditioning per conditioned surface unit",
                "Energy bill for lighting per gross internal surface unit",
                "Total annual revenues, sum of discounted annual revenues and annuity",
                "Energy production costs",
                "Building heat transfer coefficient (U value)",
                "Reduction in annual final energy consumption",
                "Total residential electrical energy use per capita (core indicator)", 
                "Use of renewable energy",
                "Percentage of Renewable energy use",
                "Annual final energy consumption", 
                "Carbon dioxide emission in tonnes reduction", 
                "Reduction in lifecycle CO2 emissions in tonnes",
                "CO2 emissions associated with the heating for buildings",
                "CO2 produced from electricity usage per m2 of floor area",
                "Energy performance gap (EPG)",
                "Energy savings",
                "Reduction of CO2",
                "GWP - GhGs",
                "Energy class of the building",
                "Sustainable resource use",
                ],
                formats: [
                    "Electric/Thermal/etc.",
                    "toe",
                    "toe",
                    "(toe/m3* y)*1000",
                    "(toe/m2* y)*1000",
                    "(toe/m2 Nrg *y)*1000",
                    "kWhe/m2 Nrg *y",
                    "kWhe/m2 *y",
                    "kWht/m2 Nrg *y",
                    "kWht/m2 *y",
                    "kWhe/m2 Nrg *y",
                    "kWht/m2 Nrg * DD*y",
                    "kWhe/m2 Nrg * DD*y",
                    "kWe",
                    "kWt",
                    "€/ m2 *y",
                    "€/ m2 *y",
                    "€/ m2 *y",
                    "€/ m2Nrg *y",
                    "€/ m2 *y",
                    "€/year",
                    "€/kWh",
                    "kW/m2/K",
                    "% in kWh",
                    "kWh/y/cap",
                    "Yes/no",
                    "%",
                    "kWh/y", 
                    "%", 
                    "%",
                    "tCO2/y",
                    "tCO2/m2",
                    "EPG=(E2-E1)/E1",
                    "Kwh",
                    "tCO2",
                    "kg CO2 eq",
                    "A-G",
                    "% or scale, typology etc."
                ],
                values:[
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                ]
        },
        KPI_ENVIRONMENTAL_TOBE: {
            names: ['LCA Indicator'],
            formats: ['kgCO2eq'],
            values: ['0']
        },
        KPI_SOCIAL_TOBE: {
            names: [
                'Flexibility',
                'Occupant satisfaction',
                'Feeling of safety',
                'Cultural heritage',
                'Increased environmental/sustainability',
                'education',
                'Community acceptance',
                'Arrears on utility bills',
                'Hidden energy poverty(HEP)',
                'Inability to keep home adequately warm',
                'Fuel oil prices',
                'Biomass prices',
                'Coal prices',
                'Household electricity prices',
                'District heating prices',
                'Household gas prices',
                'Dwelling comfortably cool during summer time',
                'Number of rooms per person, owners',
                'Dwelling comfortably warm during winter time',
                'Number of rooms per person, renters',
                'Dwellings in densely populated areas',
                'Number of rooms per person, total',
                'Dwellings in intermediately populated areas',
                'Poverty risk',
                'Dwellings with energy label A',
                'Energy expenses, income quintile 1',
                'Energy expenses, income quintile 2',
                'Energy expenses, income quintile 3',
                'Energy expenses, income quintile 4',
                'Energy expenses, income quintile 5',
                'Equipped with air conditioning',
                'Equipped with heating'
            ],
            formats: [
                'Degree in % or scale',
                '% or scale',
                '% or scale',
                'yes/no',
                'scale or %',
                'scale or %',
                '% or scale',
                '€',
                '€',
                '€',
                '% or scale',
                '€',
                '€',
                '€',
                '€',
                '€',
                '€',
                'number',
                'number',
                'number',
                'number',
                'number',
                'number',
                'number',
                '%',
                'number',
                '€',
                '€',
                '€',
                '€',
                '€',
                'yes/no',
                'yes/no'
            ],
            values: [
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0",
                "0"
            ]
        },
        KPI_COMFORT_TOBE: {
            names: [
                'Room temperature',
                'Thermal comfort / Humidity',
                'CO2 concentration',
                'Formaldehyde (HCHO) concentration',
                '% time inside the hygrothermal zone',
                'Total VOCs (PM2.5, PM10, PM20)'
            ],
            formats: [
                '°C degrees',
                '%',
                'mg/m3, ppm',
                'mg/m3, ppm',
                '%',
                'ug/m3, ppm'
            ],
            values: [
                '0',
                '0',
                '0',
                '0',
                '0',
                '0'
            ]
        },       
    }
}

module.exports = common
